# 脚本机器人的名字
name: 'BirthdayBot'

# 触发条件
on:
  push:
  workflow_dispatch:
  watch:
    types: [ started ]
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENDER: ${{ secrets.SENDER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      RECEIVERS: ${{ secrets.RECEIVERS }}
      KEY: ${{ secrets.KEY }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      # 使用actions/checkout@v4获取仓库代码
      - name: 'Checkout'
        uses: actions/checkout@v4

      # 设置 node 环境
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 指定 Node.js 版本
          cache: 'npm'       # 启用 npm 缓存

      # 执行
      - name: 'Run Project'
        run: npm install && npm run server # 安装依赖，执行server
      
      # 测试 index.js 测试
      - name: 'Test Index.js'
        run: node index.js